// ==UserScript==
// @name         Preview Steam Background on Sapic
// @namespace    http://oddball.tf
// @version      2.7
// @description  Adds a Sapic preview button to Steam Market background listings
// @author       The Oddball
// @include      /http:\/\/steamcommunity\.com\/.*/
// @include      /https:\/\/steamcommunity\.com\/.*/
// @include      /http:\/\/www.steamcardexchange.net\/.*/
// @include      /https:\/\/www.steamcardexchange.net\/.*/
// @grant        none
// @downloadURL  https://github.com/theoddball/sapic-preview-button/raw/master/sapic-preview-button.user.js
// @updateURL    https://github.com/theoddball/sapic-preview-button/raw/master/sapic-preview-button.meta.js
// ==/UserScript==
function load(){var t=window.location.hostname,e=/steamcommunity/.test(t),n=/steamcardexchange/.test(t),i=window.location.href;e?/\/753\//.test(i)?scmSapicButton():/\/inventory\//.test(i)?invSapicButton():/\/edit/.test(i)&&settingsSapicButton():n&&/gamepage-appid/.test(i)&&sceSapicButton()}function scmSapicButton(){var t=$J,e=t("#largeiteminfo_item_actions").find("a");if(e.length){var n=e.attr("href");/public\/images\/items/.test(t(e).attr("href"))&&e.after('<a class="scm_sapic_button btn_small btn_grey_white_innerfade" target="_blank" href="https://steam.design/#'+n+'"><span>Preview on Sapic</span></a>')}}function invSapicButton(){var t=$J;setInterval(function(){var e=t(".inventory_iteminfo").find(".item_desc_content").find(".item_desc_description").find("#iteminfo1_item_actions"),n=t(e).find("a").first();if(n.length){var i=/public\/images\/items/.test(t(n).attr("href")),a=n.attr("href");i&&!e.find(".inv_sapic_button:not(#iteminfo0_item_actions)").length&&n.after('<a class="inv_sapic_button btn_small btn_grey_white_innerfade" target="_blank" href="https://steam.design/#'+a+'"><span>Preview on Sapic</span></a>')}},200),setInterval(function(){var e=t(".inventory_iteminfo").find(".item_desc_content").find(".item_desc_description").find("#iteminfo0_item_actions"),n=t(e).find("a").first();if(n.length){var i=/public\/images\/items/.test(t(n).attr("href")),a=n.attr("href");i&&!e.find(".inv_sapic_button:not(#iteminfo1_item_actions)").length&&n.after('<a class="inv_sapic_button btn_small btn_grey_white_innerfade" target="_blank" href="https://steam.design/#'+a+'"><span>Preview on Sapic</span></a>')}},200)}function settingsSapicButton(){var t=$J;setInterval(function(){var e=t("#profile_background_current_image").attr("src"),n=t(".settings_sapic_button");e=e.replace("?size=140x90&v=2",""),t(".background_selector_launch_area").find(".btn_grey_white_innerfade.btn_small").first().before('<a class="settings_sapic_button btn_small btn_grey_white_innerfade" style="margin-right: 10px;" target="_blank" href="https://steam.design/#'+e+'"><span>Preview on Sapic</span></a>'),n.remove()},200)}function sceSapicButton(){$(".showcase-element").find(".button-blue.preview").each(function(){var t=$(this).parent().parent().find(".element-link-right").attr("href");$(this).parent().find(".button-blue.preview").before('<a class="button-blue" style="bottom: 5px;" target="_blank" href="https://steam.design/#'+t+'"><span>Preview on Sapic</span></a>')}),$(".button-blue.market").each(function(){$(this).css("top","175px")})}load();